version: '3.3'
services:
  nodejs:
    build:
      # build from Dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    env_file:
      - '.env'
  mongo:
    container_name: node-gmp-db-mongo
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db-data:/db
