version: "3.9"
services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
        - MONGODB_URI=mongodb://mongo:27017/node-gmp-db-mongo
    depends_on:
      - mongo
    networks:
      - my_network
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - my_network
networks:
  my_network:
